# install numpy (mac)- !pip install numpy

In [ ]:
pip install numpy  #windows

In [3]:
import numpy as np
matrix=[[1,2,3],[4,5,6],[11,22,33]]

In [4]:
arr = np.array(matrix)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33]])

In [5]:
len(arr)  #dimensions

3

In [6]:
arr.size  #number of elements

9

In [11]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr.dtype  #type of an array

dtype('int32')

In [15]:
arr= np.zeros(4)
print(arr)
print(arr.dtype)

[0. 0. 0. 0.]
float64


In [17]:
arr= np.ones(4, dtype='int')
print(arr)
print(arr.dtype)

[1 1 1 1]
int32


In [19]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
arr = np.eye(4)  #identity matrix
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
arr.T   #transpose of a matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.linspace (0,10,4)  # leanerly spaced number from 0 to 10 with a spcae of 4

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [32]:
np.linspace(0,10,50)  # leaner space 50 numbers bet 0 to 10, with a gap of 50

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [34]:
np.random.rand(3)  # 3 random numbers, between 0 to 1

array([0.5870838 , 0.28579413, 0.92518729])

In [37]:
np.random.seed(123)   # seed number
np.random.rand(3)

array([0.69646919, 0.28613933, 0.22685145])

In [38]:
np.random.seed(123)   # seed will repeat the random numbers
np.random.rand(3)

array([0.69646919, 0.28613933, 0.22685145])

In [40]:
np.random.randn(4)   # unsigned number (standard normal distribution)

array([-0.05151772, -0.20420096,  1.97934843, -1.61930007])

# random integer

In [42]:
np.random.randint(1,100)  # number bet 1 to 100

84

In [43]:
np.random.randint(1,50,4)

array([15, 37, 33, 17])

In [46]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.shape   # tuple

(25,)

In [50]:
arr2= arr.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr2.shape   #tuple/Dimension

(5, 5)

In [55]:
arr2.reshape(1, 25)  # connver to 1 row and 25 colls

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [56]:
arr2.reshape(25,1)   #convert to 1 coll, 25 rows

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [57]:
arr2.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
arr= np.random.randint(1,100,10)
arr

array([56, 68,  3, 85, 40, 67, 85, 48, 62, 49])

In [63]:
arr.max()

85

In [64]:
arr.min()

3

In [65]:
arr.argmax() #position of max ele

3

In [69]:
arr= np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr[-7]   # read from backward

3

In [71]:
#slice an array
arr[6:]

array([6, 7, 8, 9])

In [73]:
arr[1:5]=200 #broadcasting
arr

array([  0, 200, 200, 200, 200,   5,   6,   7,   8,   9])

In [74]:
arr2=arr
print(arr)
print(arr2)
arr is arr2    #pointing to same object

[  0 200 200 200 200   5   6   7   8   9]
[  0 200 200 200 200   5   6   7   8   9]


True

In [75]:
arr2=arr.copy()   # make a seperate copy in memory
print(arr)
print(arr2)
arr is arr2    #pointing to different object

[  0 200 200 200 200   5   6   7   8   9]
[  0 200 200 200 200   5   6   7   8   9]


False

In [76]:
arr= np.array([1,2,3,4,5])
arr[2]

3

In [79]:
arr= np.array([[1,2,3],[4,5,6],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [80]:
arr[0,2]

3

In [81]:
arr[0][2]

3

In [83]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [84]:
arr[:2, :2]

array([[1, 2],
       [4, 5]])